### ISSUE TITLE
Add fuzzy matching to case lookup

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/EfileProxyServer#26]
Some thoughts:

1. Try common name reversals/mixups of first/middle/last
2. Use reverse SOUNDEX matching? There could be a much better solution, but something like it. https://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/language/Soundex.html. Also see "reverse soundex" (might be a more formal name for going from SOUNDEX code to English equivalents) https://stevemorse.org/dl/reversesoundex.html?soundexcode=S352

This could be a helpful research point: https://www.rosette.com/blog/overview-fuzzy-name-matching-techniques/

**Comment by BryceStevenWilley** [comment]
This would be super useful, but on the Tyler-side, case lookup is really slow (on a popular name as input, it can take 45-60 seconds just to return the list of case numbers for all of the found cases). Trying to smartly do multiple searches for fuzzy matching is a good idea, but would take long enough that it would require engineering effort to handle a queue of tasks (and have a sane UI on the DA / user side), that I don't know how to start tackling it. Pushing this back a little further.

**Comment by BryceStevenWilley** [comment]
Yeah, I'm leaning towards the fact that this won't happen. There's nothing that we can really do on the server side to speed things up, and we'd have the best information about how to search for more names and such on the docassemble side. Going to close this one.
