### ISSUE TITLE
end_date in get_filing_status seems to be exclusive of the end date; that's a bit confusing

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/EfileProxyServer#50]
https://github.com/SuffolkLITLab/EfileProxyServer/blob/01d941fe15e00fca60b68d5513b1cfd2be52f4b7/src/main/java/edu/suffolk/litlab/efspserver/services/FilingReviewService.java#L93

It makes it harder to look up the status of cases filed on the current day. I've adjusted in the admin interface but it probably makes sense to use <= instead of < in the relevant place. It wasn't something I could quickly find

**Comment by BryceStevenWilley** [comment]
This isn't something we control, we just pass it through to the Tyler search. We can better rename it to avoid confusion though.
